baseURL = 'http://localhost:1313'
languageCode = 'en-us'
title = 'Bee Sharpe'
theme = 'portfolio'


[params]
# Style options: default (pink), blue, green, pink, red, sea, violet
# Use custom.css for your custom styling
sidebarAbout = [
    "Hi! My name is Bee and Im a problem solver. \n \n Currently, I am an operations engineer at think-cell Software, a leading provider of software solutions for data visualization and presentation. With over five years of experience in technical consultation and project management, I have successfully delivered various projects for clients across different industries and domains, such as Meta, Google, and Amazon. ",
]
style = "default"
description = "Portfolio of Bee Sharpe"
copyright = "&copy;2024 Bee Sharpe"
# Contact page
# Since this template is static, the contact form uses www.formspree.io as a
# proxy. The form makes a POST request to their servers to send the actual
# email. Visitors can send up to a 1000 emails each month for free.
#
# What you need to do for the setup?
#
# - set your email address under 'email' below
# - upload the generated site to your server
# - send a dummy email yourself to confirm your account
# - click the confirm link in the email from www.formspree.io
# - you're done. Happy mailing!
email = "bees@hey.com"

# Optional Matomo analytics (formerly piwik)
# [params.analytics.matomo]
#  URL = "https://stats.example.com"
#  ID = "42"
#  # Track all subdomains with "*.example.com" (Optional)
#  domain = "www.example.com"
#  # Optional integrity check hash
#  hash = ""

# Nav links in the side bar
[[params.navlinks]]
name = "Home"
url = "portfolio/"
home = true

[[params.navlinks]]
name = "About"
url = "about/"

[[params.navlinks]]
name = "Get in touch"
url = "contact/"

[params.social]
email = "bees@hey.com"
linkedin = "https://www.linkedin.com/in/beesharpe/"
github = "https://github.com/ziggi24"
